// The CLAUDE.md / AGENTS.md managed-block writer. Terminal Hub only ever owns the text BETWEEN a
// block's markers; everything a user hand-authors outside them is preserved byte-for-byte. A block
// is replaced in place on every re-write, so writing a folder repeatedly never grows a second copy.
//
// Two independent block types share these files: the space-wizard config (SPACE-CONFIG, the default)
// and the agent system prompt (SYSTEM-PROMPT). Each is delimited by its OWN marker pair, so they
// coexist in one CLAUDE.md/AGENTS.md and updating one never disturbs the other.

export interface ManagedMarkers {
  start: string;
  end: string;
  header: string; // sits above the block ONLY on a brand-new file, explaining where it came from
}

export const BLOCK_START = "<!-- TERMINALHUB:SPACE-CONFIG START (generated — edit in the space wizard) -->";
export const BLOCK_END = "<!-- TERMINALHUB:SPACE-CONFIG END -->";

/** The space-wizard config block (the default — what seeder.ts writes). */
export const SPACE_CONFIG_MARKERS: ManagedMarkers = {
  start: BLOCK_START,
  end: BLOCK_END,
  header: "<!-- Generated by Terminal Hub. Edits OUTSIDE the TERMINALHUB:SPACE-CONFIG block below are preserved. -->",
};

/** The agent system-prompt block (the effective global ⊕ workspace ⊕ terminal prompt). */
export const SYSTEM_PROMPT_MARKERS: ManagedMarkers = {
  start: "<!-- TERMINALHUB:SYSTEM-PROMPT START (generated — edit in agent system-prompt settings) -->",
  end: "<!-- TERMINALHUB:SYSTEM-PROMPT END -->",
  header: "<!-- Generated by Terminal Hub. Edits OUTSIDE the TERMINALHUB:SYSTEM-PROMPT block below are preserved. -->",
};

/** The delimited block wrapping the given content (already trimmed). */
function block(content: string, m: ManagedMarkers): string {
  return `${m.start}\n${content}\n${m.end}`;
}

/** Strip an existing managed block (and the blank lines hugging it) out of a file's content. */
function stripBlock(existing: string, m: ManagedMarkers): string {
  const start = existing.indexOf(m.start);
  const end = existing.indexOf(m.end);
  if (start === -1 || end === -1) return existing;
  const before = existing.slice(0, start).replace(/\s+$/, "");
  const after = existing.slice(end + m.end.length).replace(/^\s+/, "");
  if (!before) return after ? after + "\n" : "";
  if (!after) return before + "\n";
  return `${before}\n\n${after}\n`;
}

/**
 * Apply a Terminal Hub managed block (selected by `markers`, default SPACE-CONFIG) to a
 * CLAUDE.md/AGENTS.md.
 * - `existing` null/empty → create the file (header + block).
 * - this block's markers already present → replace it in place (idempotent; surrounding text — and
 *   any OTHER managed block — untouched).
 * - markers absent → insert at the top (`pin`) or bottom (`append`).
 * - empty `content` → remove this managed block if one exists; otherwise leave the file untouched.
 */
export function applyManagedBlock(
  existing: string | null,
  content: string,
  mode: "pin" | "append",
  markers: ManagedMarkers = SPACE_CONFIG_MARKERS,
): string {
  const trimmed = content.trim();
  const hasMarkers = !!existing && existing.includes(markers.start) && existing.includes(markers.end);

  if (!trimmed) {
    return hasMarkers ? stripBlock(existing!, markers) : (existing ?? "");
  }

  const b = block(trimmed, markers);

  if (hasMarkers) {
    const start = existing!.indexOf(markers.start);
    const end = existing!.indexOf(markers.end) + markers.end.length;
    return existing!.slice(0, start) + b + existing!.slice(end);
  }

  if (!existing || !existing.trim()) {
    return `${markers.header}\n\n${b}\n`;
  }

  return mode === "pin"
    ? `${b}\n\n${existing.replace(/^\s+/, "")}`
    : `${existing.replace(/\s+$/, "")}\n\n${b}\n`;
}
