import { describe, it, expect } from "vitest";
import { applyManagedBlock, BLOCK_START, BLOCK_END } from "./managedBlock.js";

describe("applyManagedBlock", () => {
  it("creates a new file with a header + delimited block when there is no existing content", () => {
    const out = applyManagedBlock(null, "Always use TDD.", "append");
    expect(out).toContain(BLOCK_START);
    expect(out).toContain(BLOCK_END);
    expect(out).toContain("Always use TDD.");
    // a generated-file header sits above the block on a brand-new file
    expect(out.indexOf("Generated by Terminal Hub")).toBeLessThan(out.indexOf(BLOCK_START));
  });

  it("inserts the block at the TOP in pin mode, leaving hand-authored content below untouched", () => {
    const existing = "# My Project\n\nHand-written notes.\n";
    const out = applyManagedBlock(existing, "Pinned rule.", "pin");
    expect(out.indexOf(BLOCK_START)).toBeLessThan(out.indexOf("# My Project"));
    expect(out).toContain("Hand-written notes.");
  });

  it("appends the block at the BOTTOM in append mode, leaving hand-authored content above untouched", () => {
    const existing = "# My Project\n\nHand-written notes.\n";
    const out = applyManagedBlock(existing, "Appended rule.", "append");
    expect(out.indexOf("# My Project")).toBeLessThan(out.indexOf(BLOCK_START));
    expect(out).toContain("Hand-written notes.");
  });

  it("replaces an existing managed block in place (no duplicate) on re-run", () => {
    const first = applyManagedBlock("# Keep me\n", "Rule v1.", "append");
    const second = applyManagedBlock(first, "Rule v2.", "append");
    expect(second).toContain("Rule v2.");
    expect(second).not.toContain("Rule v1.");
    // exactly one block
    expect(second.split(BLOCK_START).length - 1).toBe(1);
    expect(second).toContain("# Keep me");
  });

  it("is idempotent — applying the same content twice yields byte-identical output", () => {
    const once = applyManagedBlock("# Keep me\n\nbody\n", "Stable rule.", "append");
    const twice = applyManagedBlock(once, "Stable rule.", "append");
    expect(twice).toBe(once);
  });

  it("is idempotent in pin mode too", () => {
    const once = applyManagedBlock("# Keep me\n\nbody\n", "Stable rule.", "pin");
    const twice = applyManagedBlock(once, "Stable rule.", "pin");
    expect(twice).toBe(once);
  });

  it("removes the managed block when the content becomes empty, keeping hand-authored text", () => {
    const seeded = applyManagedBlock("# Keep me\n\nbody\n", "Temporary rule.", "append");
    const stripped = applyManagedBlock(seeded, "   ", "append");
    expect(stripped).not.toContain(BLOCK_START);
    expect(stripped).not.toContain("Temporary rule.");
    expect(stripped).toContain("# Keep me");
    expect(stripped).toContain("body");
  });

  it("leaves a marker-less file untouched when asked to write empty content", () => {
    const existing = "# Untouched\n";
    expect(applyManagedBlock(existing, "", "append")).toBe(existing);
  });
});
