// The CLAUDE.md / AGENTS.md managed-block writer. Terminal Hub only ever owns the text BETWEEN these
// markers; everything a user hand-authors outside them is preserved byte-for-byte. The block is
// replaced in place on every re-seed, so seeding a folder repeatedly never grows a second copy.

export const BLOCK_START = "<!-- TERMINALHUB:SPACE-CONFIG START (generated — edit in the space wizard) -->";
export const BLOCK_END = "<!-- TERMINALHUB:SPACE-CONFIG END -->";

// Header sits above the block ONLY on a brand-new file, so a freshly created CLAUDE.md/AGENTS.md
// explains where its content came from without polluting files the user already had.
const GENERATED_HEADER =
  "<!-- Generated by Terminal Hub. Edits OUTSIDE the TERMINALHUB:SPACE-CONFIG block below are preserved. -->";

/** The delimited block wrapping the given content (already trimmed). */
function block(content: string): string {
  return `${BLOCK_START}\n${content}\n${BLOCK_END}`;
}

/** Strip an existing managed block (and the blank lines hugging it) out of a file's content. */
function stripBlock(existing: string): string {
  const start = existing.indexOf(BLOCK_START);
  const end = existing.indexOf(BLOCK_END);
  if (start === -1 || end === -1) return existing;
  const before = existing.slice(0, start).replace(/\s+$/, "");
  const after = existing.slice(end + BLOCK_END.length).replace(/^\s+/, "");
  if (!before) return after ? after + "\n" : "";
  if (!after) return before + "\n";
  return `${before}\n\n${after}\n`;
}

/**
 * Apply Terminal Hub's managed block to a CLAUDE.md/AGENTS.md.
 * - `existing` null/empty → create the file (header + block).
 * - markers already present → replace the block in place (idempotent; surrounding text untouched).
 * - markers absent → insert at the top (`pin`) or bottom (`append`).
 * - empty `content` → remove a managed block if one exists; otherwise leave the file untouched.
 */
export function applyManagedBlock(existing: string | null, content: string, mode: "pin" | "append"): string {
  const trimmed = content.trim();
  const hasMarkers = !!existing && existing.includes(BLOCK_START) && existing.includes(BLOCK_END);

  if (!trimmed) {
    return hasMarkers ? stripBlock(existing!) : (existing ?? "");
  }

  const b = block(trimmed);

  if (hasMarkers) {
    const start = existing!.indexOf(BLOCK_START);
    const end = existing!.indexOf(BLOCK_END) + BLOCK_END.length;
    return existing!.slice(0, start) + b + existing!.slice(end);
  }

  if (!existing || !existing.trim()) {
    return `${GENERATED_HEADER}\n\n${b}\n`;
  }

  return mode === "pin"
    ? `${b}\n\n${existing.replace(/^\s+/, "")}`
    : `${existing.replace(/\s+$/, "")}\n\n${b}\n`;
}
