// Prompt builder for AI pull-request descriptions. Parallels ai/commit.ts: the model is given the
// branch's commits + changed-file list and asked to return the PR title on the first line and the
// body below it (GitHub-flavored Markdown). The user edits it before `gh pr create`, so no AI
// attribution is injected — and the default prompt explicitly forbids any attribution anyway.

const MAX = 24_000; // commit/file lists are small vs a full diff; cap as a backstop on huge branches

// The default instructions. Editable per-install via AiConfig.prPrompt; the commit list and changed
// files below are always appended by the server, so a custom prompt can't drop them.
export const DEFAULT_PR_INSTRUCTIONS = `You are an expert at writing GitHub Pull Request descriptions. You are given all of the
commits on a feature branch and the list of files it changes. Write a PR title and body
that describe the WHOLE branch, not just the latest commit.

## Output format
The FIRST line is the PR title. Everything after the first line is the PR body.

Title: a single Conventional Commits line summarizing the branch
(feat:/fix:/refactor:/docs:/style:/chore:/perf:/test:), under 72 characters. No trailing period.

Body (GitHub-flavored Markdown):
\`\`\`
## Summary
- <bullets built from the branch's commits — minimal, no padding, cover everything real>

## Notes
- <only if there is something the reviewer must know: backend dependency, follow-up,
   gotcha. Omit this entire section if there is nothing.>
\`\`\`

## Rules
- The summary must reflect the entire branch. Combine related commits into one bullet.
- Drop noise commits like "fix typo", "wip", "merge", or formatting-only churn.
- Use imperative mood ("Add" not "Added"). Be specific — name the feature, file, or
  component when it helps the reviewer.
- Do NOT invent changes that are not supported by the commits or changed files.
- Do NOT include the raw diff.
- Do NOT add any AI or assistant attribution anywhere (no "Co-Authored-By", no "Generated by").
- Do NOT add meta-commentary. Return only the title line followed by the body.`;

export function buildPrPrompt(commits: string, files: string, instructions?: string): string {
  const c = commits.length > MAX ? commits.slice(0, MAX) + "\n…(commits truncated)" : commits;
  return [
    instructions?.trim() || DEFAULT_PR_INSTRUCTIONS,
    "",
    "Commits on the branch (newest first):",
    c.trim() || "(none)",
    "",
    "Files changed:",
    files.trim() || "(none reported)",
  ].join("\n");
}

/** The model returns the PR title on the first line and the body below it. Split + trim, and strip
 *  the things models tack on anyway: a wrapping ``` code fence, a "Title:" prefix, a leading `#`. */
export function splitPrMessage(text: string): { title: string; body: string } {
  const cleaned = text.replace(/^```[a-z]*\n?/i, "").replace(/\n?```\s*$/i, "").trim();
  const nl = cleaned.indexOf("\n");
  const first = (nl === -1 ? cleaned : cleaned.slice(0, nl)).trim();
  const body = nl === -1 ? "" : cleaned.slice(nl + 1).trim();
  const title = first.replace(/^title:\s*/i, "").replace(/^#+\s*/, "").trim();
  return { title, body };
}
